"""create db

Revision ID: 43b7f61004bd
Revises: 9cdf79183d07
Create Date: 2021-07-14 16:32:57.199179

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43b7f61004bd'
down_revision = '9cdf79183d07'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('city',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), server_default='', nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hobby',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), server_default='', nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('friend',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), server_default='', nullable=True),
    sa.Column('city_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['city_id'], ['city.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('friend_mtm_hobby',
    sa.Column('friend_id', sa.Integer(), nullable=True),
    sa.Column('hobby_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['friend_id'], ['friend.id'], ),
    sa.ForeignKeyConstraint(['hobby_id'], ['hobby.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('friend_mtm_hobby')
    op.drop_table('friend')
    op.drop_table('hobby')
    op.drop_table('city')
    # ### end Alembic commands ###
